### ISSUE TITLE
Plugin doesn't load

### ISSUE THREAD

**Issue by gdude2002** [ModernDayPlayer/SurvivalGamesX#1]
This plugin appears to use `net.minecraft` for some reason? That's never a good idea, but anyway..

```
[12:12:18 ERROR]: Error occurred while enabling SurvivalGames v1.0.7 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/util/org/apache/commons/lang3/tuple/Pair
        at net.shockverse.survivalgames.extras.PropertyList.setString(PropertyList.java:126) ~[?:?]
        at net.shockverse.survivalgames.extras.PropertyList.setString(PropertyList.java:121) ~[?:?]
        at net.shockverse.survivalgames.core.Settings.setup(Settings.java:150) ~[?:?]
        at net.shockverse.survivalgames.core.Settings.load(Settings.java:82) ~[?:?]
        at net.shockverse.survivalgames.SurvivalGames.onEnable(SurvivalGames.java:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-"1ccd086"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:333) [spigot.jar:git-Spigot-"1ccd086"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot.jar:git-Spigot-"1ccd086"]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [spigot.jar:git-Spigot-"1ccd086"]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [spigot.jar:git-Spigot-"1ccd086"]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot.jar:git-Spigot-"1ccd086"]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot.jar:git-Spigot-"1ccd086"]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot.jar:git-Spigot-"1ccd086"]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot.jar:git-Spigot-"1ccd086"]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:498) [spigot.jar:git-Spigot-"1ccd086"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.org.apache.commons.lang3.tuple.Pair
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-"1ccd086"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-"1ccd086"]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
        ... 16 more
```

I've noticed that there are no build files in this repo - no pom.xml, build.gradle, eclipse workspace, etc. That's bad - I may submit a pull request later.

**Comment by gdude2002** [comment]
Pull request. #2

**Comment by SpraxDev** [comment]
Remove the imports and let youre IDE import them automatically. Bukkit also has the apache.common.lang3 Classes.
